services:
  fcp-jkr-demo-backend-1-core-tests:
    build:
      target: development
    image: fcp-jkr-demo-backend-1-core-tests-development
    container_name: fcp-jkr-demo-backend-1-core-tests
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet watch --project test/Fcp.Jkr.Demo.Backend.1.Core.Tests/Fcp.Jkr.Demo.Backend.1.Core.Tests.csproj test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./src/Fcp.Jkr.Demo.Backend.1.Core:/home/dotnet/src/Fcp.Jkr.Demo.Backend.1.Core
      - ./test/Fcp.Jkr.Demo.Backend.1.Core.Tests:/home/dotnet/test/Fcp.Jkr.Demo.Backend.1.Core.Tests
      - ./test-output:/home/dotnet/Fcp.Jkr.Demo.Backend.1.Core.Tests/test-output

  fcp-jkr-demo-backend-1-api-tests:
    build:
      target: development
    image: fcp-jkr-demo-backend-1-api-tests-development
    container_name: fcp-jkr-demo-backend-1-api-tests
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet watch --project test/Fcp.Jkr.Demo.Backend.1.Api.Tests/Fcp.Jkr.Demo.Backend.1.Api.Tests.csproj test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./src/Fcp.Jkr.Demo.Backend.1.Api:/home/dotnet/src/Fcp.Jkr.Demo.Backend.1.Api
      - ./test/Fcp.Jkr.Demo.Backend.1.Api.Tests:/home/dotnet/test/Fcp.Jkr.Demo.Backend.1.Api.Tests
      - ./test-output:/home/dotnet/Fcp.Jkr.Demo.Backend.1.Api.Tests/test-output